fix: Correct PostgreSQL database role permissions in init script
Changed GRANT from 'postgres' superuser (which doesn't exist in container)
to 'pnptv_user' which is the actual application database user.

This fixes the init script error:
  ERROR: role "postgres" does not exist
  STATEMENT: GRANT ALL PRIVILEGES ON DATABASE pnptv_bot TO postgres;